const userRepository = require("./../repositories/user.repository")

const hash = require('./../utils/hash')
const jwt = require('./../utils/jwt')

async function register(data) {
    const { name, email, password, departmentId } = data

    // Verify that the email isn't registered yet
    const emailFound = await userRepository.findByEmail(email)

    if(emailFound.length > 0) {
        console.log(emailFound)
        const error = Error("That email is already registered.")
        error.status = 400

        throw error
    }

    // Hash the password
    const passwordHash = await hash.generate(password)

    // Save in the DB
    const newUser = {
        name,
        email,
        passwordHash,
        departmentId
    }

    const id = await userRepository.create(newUser) // The query returns the id generated by the db

    // Return response
    const info = {
        id,
        name,
        email,
        message: "Account created. Admin must active the account"
    }

    return info
}

async function login(data) {
    const { email, password } = data

    // Checkings

    // 1. The email user must be registered
    const user = await userRepository.findByEmail(email)
    //console.log("USER: ", user[0])
    if(user.length == 0) {
        const err = new Error("That email isn't registered yet.")
        err.status = 401

        throw err
    } 
    // 2. The account must be active
    else if(!user[0].is_active) {
        const err = new Error("The account isn't activated. Contact an admin support to active it.")
        err.status = 401

        throw err
    }
    // 3. The password hash must match
    else if(!await hash.validate(user[0].password_hash, password)) {
        const err = new Error("The password doesn't matches")
        err.status = 401

        throw err
    }

    // Generating JWT Token
    const payload = {
        id: user[0].id,
        name: user[0].name,
        email: user[0].email,
        departmentId: user[0].department_id,
        roleId: user[0].role_id
    }

    const token = jwt.generate(payload)

    return {token}
}

module.exports = { register, login }