const userRepository = require("./../repositories/user.repository")

const hash = require('./../utils/hash')

async function register(data) {
    const { name, email, password, departmentId } = data

    // Verify that the email isn't registered yet
    const emailFound = await userRepository.findByEmail(email)

    if(emailFound.length > 0) {
        console.log(emailFound)
        const error = Error("That email is already registered.")
        error.status = 400

        throw error
    }

    // Hash the password
    const passwordHash = await hash.generate(password)

    // Save in the DB
    const newUser = {
        name,
        email,
        passwordHash,
        departmentId
    }

    const id = await userRepository.create(newUser) // The query returns the id generated by the db

    // Return response
    const info = {
        id,
        name,
        email,
        message: "Account created. Admin must active the account"
    }

    return info
}

module.exports = { register }