const userRepository = require("./../repositories/user.repository")

const hash = require('./../utils/hash')
const jwt = require('./../utils/jwt')

async function register(data) {
    const { name, email, password, department_id, rol_id } = data

    // Verify that the email isn't registered yet
    const emailFound = await userRepository.findByEmail(email)

    if(emailFound.length > 0) {
        const error = Error("That email is already registered.")
        error.status = 400

        throw error
    }

    // Hash the password
    const passwordHash = await hash.generate(password)

    // Save in the DB
    const newUser = {
        name,
        email,
        password_hash: passwordHash,
        department_id,
        rol_id
    }

    const id = await userRepository.create(newUser) // The query returns the id generated by the db

    // Create user token
    const payload = {
        id,
        name,
        email,
        department_id,
        rol_id
    }

    const token = jwt.generate(payload)

    // Return response
    return token
}

module.exports = { register }