const userRepository = require('./../repositories/user.repository')
const roleRepository = require('./../repositories/role.repository')

// GET
async function get(id) {
    // Make DB Query
    const response = await userRepository.findById(id)

    // Returning response
    return response
}
async function getAll(page, limit) {
    // Make DB Query
    const actualPage = (page-1)*limit // SQL starts from 0 | The limit is 20

    const users = await userRepository.find(actualPage, limit)

    // Returning response
    return users
}

// POST
async function add(data) {
    const { name, email, password, departmentId, roleName } = data

    // Verify that the email isn't registered yet
    const emailFound = await userRepository.findByEmail(email)

    if(emailFound.length > 0) {
        console.log(emailFound)
        const error = Error("That email is already registered.")
        error.status = 401

        throw error
    }

    // Asign role ID
    const roleId = await roleRepository.findByName(roleName)

    // Hash the password
    const passwordHash = await hash.generate(password)

    // Save in the DB
    const newUser = {
        name,
        email,
        passwordHash,
        departmentId,
        roleId,
        isActive: true // The account was created by an admin
    }

    const id = await userRepository.create(newUser) // The query returns the id generated by the db

    // Return response
    const info = {
        id,
        name,
        email,
        message: "Account created. Admin must active the account"
    }

    return info
}

// UPDATE

// DELETE
async function remove(id) {
    // Make DB Query
    const response = await userRepository.remove(id)

    // Check if the user doesn't existed
    if(response.length == 0) {
        const err = new Error("User with that ID doesn't exists")
        err.status = 401

        throw err
    }

    // Returning
    return {response}
}

module.exports = { add, get, getAll, remove }