const userRepository = require("./../repositories/user.repository")
const roleRepository = require("./../repositories/role.repository")

const hash = require('./../utils/hash')
const jwt = require('./../utils/jwt')
const nodemailer = require("./../utils/nodemailer")

async function register(data) {
    const { name, email, phone, password, departmentId } = data

    // Verify that the email isn't registered yet
    const emailFound = await userRepository.findByEmail(email)

    if(emailFound.length > 0) {
        const error = Error("That email is already registered.")
        error.status = 400

        throw error
    }

    // Hash the password
    const passwordHash = await hash.generate(password)

    // Save in the DB
    const newUser = {
        name,
        email,
        phone,
        passwordHash,
        departmentId,
        roleId: "0307d64f-1901-4c01-84c0-444bb40d03b1", // Default Role ID (Visualizer)
        isActive: false // Account must be activated by an admin
    }

    const id = await userRepository.create(newUser) // The query returns the id generated by the db

    // Return response
    const info = {
        id,
        name,
        email,
        phone,
        message: "Account created. Admin must active the account"
    }

    return info
}

async function login(email, password) {
    // Checkings

    // 1. The email user must be registered
    const user = await userRepository.findByEmail(email)

    if(user.length == 0) {
        const err = new Error("Invalid Credentials")
        err.status = 401

        throw err
    } 
    // 2. The account must be active
    else if(!user[0].is_active) {
        const err = new Error("The account isn't activated. Contact an admin support to active it.")
        err.status = 403

        throw err
    }
    // 3. The password hash must match
    else if(!await hash.validate(user[0].password_hash, password)) {
        const err = new Error("Invalid Credentials.")
        err.status = 401

        throw err
    }

    const roleName = (await roleRepository.findById(user[0].role_id)).name

    // Generating JWT Token
    const payload = {
        id: user[0].id,
        name: user[0].name,
        email: user[0].email,
        phone: user[0].phone,
        departmentId: user[0].department_id,
        roleId: user[0].role_id,
        roleName
    }
    
    const token = jwt.generate(payload)

    return {token}
}

async function resetRequest(email) {
    // Verify if the email exists
    const user = await userRepository.findByEmail(email)

    // If the email doesn't exists, return the message for avoid creating token
    if(user.length == 0) return {message: "If the email exists, a link to reset the password has been sent."};

    // Create JWT Token
    const token = jwt.generateTemp({id: user.id}, "10m")

    // Send email
    const url = `${process.env.HOST_URL}/auth/reset-password?token=${token}`
    const html = `
            <h2>Password Reset</h2>

            <p>
                Hello ${user[0].name}, we recieve a request for reset your password.
                Please follow the next link for resetting the password
                <a href="${url}">Click Here</a>
            </p>

            <p>If you don't request a reset password, please ignore this email.</p>
        `

    await nodemailer.sendImportant({
        addressee: email,
        subject: "Reseting password - Eventger JS",
        description: html
    })

    // Returning response
    return {message: "If the email exists, a link to reset the password has been sent."}
}

async function resetPassword(token, newPassword) {
    // Verifying token
    const payload = jwt.verify(token)

    if(!payload) {
        const err = new Error("Bad Token")
        err.status = 401

        throw err
    }

    // Hashing password
    const passwordHashed = await hash.generate(newPassword)

    // Replacing it in DB
    await userRepository.updatePassword(passwordHashed, payload.id)

    // Returning response
    return {message: "Password resetted with success"}
}

module.exports = { register, login, resetRequest, resetPassword }