const userRepository = require('./../repositories/user.repository')
const roleRepository = require('./../repositories/role.repository')

const hash = require("./../utils/hash")

// GET
/*
Dynamic search in sql. If there isn't any parameter, it will return a list
of the first 50 users getted. This is by a WHERE 1=1 clause, that will be always true
*/
async function get(filters) {
    let result;

    // Making query
    result = await userRepository.search(filters)

    // Returning response
    return result
}
async function getByPage(page, limit) {
    // Make DB Query
    const actualPage = (page-1)*limit // SQL starts from 0 | The limit is 20

    const users = await userRepository.find(actualPage, limit)

    // Returning response
    return users
}
async function getById(id) {
    // Make DB Query
    const response = await userRepository.findById(id)

    // Checking the user exists
    if(!response) {
        const err = new Error("User with that ID doesn't exists")
        err.status = 401

        throw err
    }

    // Returning response
    return response[0]
}

// POST
async function add(data) {
    const { name, email, phone, password, departmentId, roleName } = data

    // Verify that the email isn't registered yet
    const emailFound = await userRepository.findByEmail(email)

    if(emailFound.length > 0) {
        const error = Error("That email is already registered.")
        error.status = 401

        throw error
    }

    // Asign role ID
    const roleId = await roleRepository.findByName(roleName)

    // Hash the password
    const passwordHash = await hash.generate(password)

    // Save in the DB
    const newUser = {
        name,
        email,
        phone,
        passwordHash,
        departmentId,
        roleId,
        isActive: true // The account was created by an admin
    }

    const id = await userRepository.create(newUser) // The query returns the id generated by the db

    // Return response
    const info = {
        id,
        name,
        email,
        phone,
        message: "Account created. The account is active"
    }

    return info
}

// UPDATE
async function update(data, id) {
    const { name, email, phone, departmentId, roleName, isActive } = data

    // Asign role ID
    const roleId =  (await roleRepository.findByName(roleName)).id

    // Save in the DB
    const updatedUser = {
        name,
        email,
        phone,
        departmentId,
        roleId,
        isActive
    }
    
    const response = await userRepository.update(updatedUser, id)

    // Return response
    return response
}
async function updateDynamic(data, id) {
    // Checking if there isn't any query
    if(Object.keys(data).length == 0) return {message: "Nothing to date."};
    console.log(data)
    // Converting role name into id (if it exists)
    if(data?.role_id) {
        const userRole = (await roleRepository.findByName(data.role_id)).id

        data.role_id = userRole;
    }

    // Calling query
    const results = userRepository.updateDynamic(data, id)

    // Returning response
    return results
}

// DELETE
async function remove(id) {
    // Make DB Query
    const response = await userRepository.remove(id)

    // Check if the user doesn't existed
    if(response.length == 0) {
        const err = new Error("User with that ID doesn't exists")
        err.status = 401

        throw err
    }

    // Returning
    return response
}

module.exports = { add, get, getByPage, getById, update, updateDynamic, remove }