// Creation of the token for requests between client and server

/*
    Made with JWT (JSON-Web-Token)

    It's composed as HEADER.PAYLOAD.SIGNATURE
        HEADER: it's the ID of the token
        PAYLOAD: The dates needed, as userId or roles
        SIGNATURE: "signature" that makes sure that nobody has modified the token
*/

const jwt = require('jsonwebtoken');

// Secret Var
const SECRET_KEY = process.env.JWT_SECRET || "secret_password_here";

// Token Duration
const EXPIRES_IN = process.env.JWT_EXPIRES || "24h"


// Return a JWT Generated Token as String
function generate(payload) {
    // Will create a encrypted token with the next structure: HEADER.PAYLOAD.SIGNATURE
    return jwt.sign(payload, SECRET_KEY, {expiresIn: EXPIRES_IN});
}

function generateTemp(payload, time) {
    return jwt.sign(payload, SECRET_KEY, { expiresIn: time })
}

/*
    Verify a token with the secret server password, for avoid manuals tokens 
    generated by the user.
    If the token is valid, you will can access to his payload data.
*/
function verify(token) {
    // Will return an error if the token isn't valid. Must be inside a try/catch
    return jwt.verify(token, SECRET_KEY)
}

module.exports = {
    generate,
    generateTemp,
    verify
}